apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: user
rules:
  # allow all verbs on app workloads (deployments, statefulsets, etc.)
  - apiGroups: ["apps"]
    resources: ["*"]
    verbs: ["*"]
  # core resources including pods and logs
  - apiGroups: [""]
    resources: ["pods", "pods/log", "services", "persistentvolumeclaims", "configmaps", "secrets", "serviceaccounts", "events", "services/proxy"]
    verbs: ["*"]
  # batch workloads (jobs, cronjobs)
  - apiGroups: ["batch"]
    resources: ["*"]
    verbs: ["*"]
  # autoscaling resources
  - apiGroups: ["autoscaling"]
    resources: ["*"]
    verbs: ["*"]
  # metrics access (read-only)
  - apiGroups: ["metrics.k8s.io"]
    resources: ["pods", "nodes"]
    verbs: ["get", "list", "watch"]
