apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # reference: https://rook.io/docs/rook/v1.12/CRDs/Cluster/external-cluster/#manifest-installation
  - https://raw.githubusercontent.com/rook/rook/refs/tags/v1.17.3/deploy/examples/crds.yaml
  - https://raw.githubusercontent.com/rook/rook/refs/tags/v1.17.3/deploy/examples/operator.yaml
  - https://raw.githubusercontent.com/rook/rook/refs/tags/v1.17.3/deploy/examples/common.yaml
  # patched ceph cluster
  - cluster-external.yaml
  # patched storage classes
  - storage-class/ceph-rbd.yaml
  - storage-class/cephfs.yaml
  - storage-class/localpath.yaml
