apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
helmCharts:
  # CNI: cillium
  - repo: https://charts.rook.io/release
    name: cilium
    namespace: kube-system
