apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
helmCharts:
  # rook operator
  - repo: https://charts.rook.io/release
    name: rook-ceph
    namespace: rook-ceph
    valuesInline:
      enableDiscoveryDaemon: true
