apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: dex
  namespace: kube-system
spec:
  parentRefs:
  - name: gateway
    namespace: kube-system
  rules:
  - backendRefs:
    - name: dex
      port: 5556
    matches:
    - path:
        type: PathPrefix
        value: /dex
