apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
resources:
  - http-route.yaml
  - rbac-storage.yaml
helmCharts:
  - repo: https://charts.dexidp.io
    releaseName: "dex"
    name: dex
    valuesInline:
      serviceAccount:
        # fix service account name
        name: dex
      volumeMounts:
        - name: dex-ca
          mountPath: /etc/certs
          readOnly: true
      volumes:
        - name: dex-ca
          secret:
            # TODO: change to org 
            secretName: p-ntuhpc-com-tls
      envFrom:
        # mount oauth client credentials as env vars
        # MICROSOFT_CLIENT_ID, MICROSOFT_CLIENT_SECRET
        - secretRef:
            name: microsoft-oauth2
      config:
        issuer: https://p.ntuhpc.com/dex
        frontend:
          issuer: NTUkjHPC
          # ntuhpc github profile picture
          logoURL: https://avatars.githubusercontent.com/u/19302960
          theme: dark
        # store data in k8s cluster
        storage:
          type: kubernetes
          config:
            inCluster: true
        # specify path to certs used by dex to sign the tokens it issues
        web:
          tlsCert: /etc/certs/tls.crt
          tlsKey: /etc/certs/tls.key
        # don't prompt the user for oauth2 scope approval
        oauth2:
          skipApprovalScreen: true
        connectors:
          - type: microsoft
            id: microsoft
            name: Microsoft
            config:
              clientId: $MICROSOFT_CLIENT_ID
              clientSecret: $MICROSOFT_CLIENT_SECRET
              redirectURI: https://p.ntuhpc.com/dex/callback
        staticClients:
        - id: k8s-control.ntuhpc.org
          name: Kubelogin for NTUHPC kubernetes Cluster
          redirectURIs:
            # redirect urls for localhost kubelogin
            - http://localhost:8000
            - http://localhost:18000
          public: true
