apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager
resources:
  - https://github.com/cert-manager/cert-manager/releases/download/v1.17.2/cert-manager.yaml
  - issuers/letsencrypt-staging.yaml
  - issuers/letsencrypt-production.yaml
patches:
  # patch the cert-manager controller to support gateway api
  - target:
      kind: Deployment
      name: cert-manager
      namespace: cert-manager
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --enable-gateway-api=true
