apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # nvidia-device-plugin
  - https://raw.githubusercontent.com/NVIDIA/k8s-device-plugin/v0.17.2/deployments/static/nvidia-device-plugin.yml
  # cert manager
  - https://github.com/cert-manager/cert-manager/releases/download/v1.17.2/cert-manager.yaml
  # monitoring stack: kube-prometheus stack
  - kube-prometheus
  # storage: PVE ceph cluster
  - rook-ceph
  - rbac
helmCharts:
  # CNI & ingress: cillium
  - repo: https://helm.cilium.io
    name: cilium
    namespace: kube-system
    valuesInline:
      # needed for ingressController
      nodePort:
        enabled: true
      ingressController:
        enabled: true
        default: true
        # share 1 loadbalancer service for all ingress resources
        loadbalancerMode: shared
