apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ingress-nginx
  - nvidia-device-plugin
helmCharts:
  # CNI: cillium
  - repo: https://helm.cilium.io
    name: cilium
    namespace: kube-system
