apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # ingress: ingress-nginx
  - https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.12.2/deploy/static/provider/cloud/deploy.yaml
  # nvidia-device-plugin
  - https://raw.githubusercontent.com/NVIDIA/k8s-device-plugin/v0.17.2/deployments/static/nvidia-device-plugin.yml
  # cert manager
  - https://github.com/cert-manager/cert-manager/releases/download/v1.17.2/cert-manager.yaml
  # monitoring stack: kube-prometheus stack
  - ./kube-prometheus

helmCharts:
  # CNI: cillium
  - repo: https://helm.cilium.io
    name: cilium
    namespace: kube-system
